MasterMarketplace/urls.py
"""
MasterMarketplace URL Configuration

"""
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    # path('osiris/', include('osiris.urls')),
    path('', include('index.urls')),
    path('accesscontrol/', include('accesscontrol.urls')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/', include('api.urls')),
    path('download/', include('download.urls')),
    path('godpowers/', include('godpowers.urls')),
    path('impersonate/', include('impersonate.urls')),
    path('js_error_hook/', include('django_js_error_hook.urls')),
    path('projects/', include('projects.urls')),
    path('registration/', include('registration.urls')),
    path('students/', include('students.urls')),
    path('studyguide/', include('studyguide.urls')),
    path('support/', include('support.urls')),
    path('tracking/', include('tracking.urls')),
    path('two_factor/', include('two_factor_custom.urls')),
    path('shen/', include('shen_ring.urls')),

]

if settings.DEBUG and False:
    import debug_toolbar

    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),

    ] + urlpatterns

# static download path, for unprotected downloads. Not used.
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers.
handler400 = 'index.views.error400'
handler404 = 'index.views.error404'
handler403 = 'index.views.error403'
handler500 = 'index.views.error500'

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.api_info, name='api'),

    # path('status/upgrade/<int:pk>/', views.upgrade_status_api, name='upgradestatus'),
    # path('status/downgrade/<int:pk>/', views.downgrade_status_api, name='downgradestatus'),
    # path('getgroupadmins/', views.get_group_admins, name='getgroupadmins'),
    # path('getgroupadmins/<str:group>/', views.get_group_admins, name='getgroupadminsarg'),
    path('projects/', views.list_published_api, name='listpublished'),
    path('projects/group/', views.list_public_projects_api, name='listpublishedpergroup'),
    path('projects/titles/', views.list_public_projects_titles_api, name='listpublishedtitles'),
    path('projects/<int:pk>/', views.detail_proposal_api, name='getpublisheddetail'),
    path('getgroupadmins/<slug:type>/', views.get_group_admins, name='getgroupadmins'),
    path('getgroupadmins/<slug:type>/<int:pk>/', views.get_group_admins, name='getgroupadmins'),
    path('verify/assistant/<int:pk>/', views.verify_assistant, name='verifyassistant'),

]

index/urls.py
from django.shortcuts import HttpResponse
from django.urls import path
from shen_ring.views import login

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', login, name='login'),  # internal call to djangosaml2 login
    path('logout/', views.logout, name='logout'),  # Saml logout doesn't work, so only local logout.
    path('profile/', views.profile, name='profile'),
    path('feedback/form/', views.feedback_form, name='feedback_form'),
    path('feedback/submit/', views.feedback_submit, name='feedback_submit'),
    path('feedback/list/', views.list_feedback, name='list_feedback'),
    path('feedback/confirm/<int:pk>/', views.feedback_confirm, name='confirm_feedback'),
    path('feedback/close/<int:pk>/', views.feedback_close, name='close_feedback'),
    path('about/', views.about, name='about'),
    path('profile/settings/', views.user_settings, name='changesettings'),
    path('terms/', views.terms_form, name='termsaccept'),
    path('robots.txt', lambda r: HttpResponse("User-agent: *\nAllow: /", content_type="text/plain"), name='robots'),  # allow all robots.
    path('markdown/upload/', views.markdown_upload, name='markdown_upload'),
]

projects/urls.py
from django.urls import path, re_path

from . import views

app_name = 'projects'

urlpatterns = [
    path('list/', views.list_public_projects, name='list'),
    path('favorites/', views.list_favorite_projects, name='favorites'),

    path('list/<str:type_filter>/', views.list_public_projects, name='list'),
    path('favorites/<str:type_filter>/', views.list_favorite_projects, name='favorites'),

    path('group/active/', views.list_group_projects, name='listgroupprojects'),
    path('group/<str:status_filter>/', views.list_group_projects, name='listgroupprojects'),

    path('details/<int:pk>/', views.detail_project, name='details'),
    path('create/', views.create_project, name='create'),
    path('own/active/', views.list_own_projects, name='chooseedit'),  # for if no kwargs given, default to active.
    path('own/<str:status_filter>/', views.list_own_projects, name='chooseedit'),
    path('edit/<int:pk>/', views.edit_project, name='edit'),
    path('copy/<int:pk>/', views.copy_project, name='copy'),

    path('files/add/<str:ty>/<int:pk>/', views.add_file, name='addfile'),
    path('files/edit/<str:ty>/<int:pk>/', views.edit_file, name='editfile'),

    path('delete/ask/<int:pk>/', views.ask_delete_project, name='askdeleteproject'),
    path('delete/<int:pk>/', views.delete_project, name='deleteproject'),

    path('labels/', views.list_labels, name='labels'),
    path('labels/add/', views.add_label, name='createlabel'),
    path('labels/<int:pk>/', views.edit_label, name='editlabel'),
    path('labels/activate/<int:pk>/', views.activate_label, name='activatelabel'),
    path('labels/delete/<int:pk>/', views.delete_label, name='deletelabel'),

    path('status/upgrade/<int:pk>/', views.upgrade_status, name='upgradestatus'),
    path('status/downgrade/<int:pk>/', views.downgrade_status, name='downgradestatusmessage'),

    # cpv
    path('contentpolicy/', views.content_policy_view, name='contentpolicy'),
    path('contentpolicy/calc/', views.content_policy_calc, name='contentpolicycalc'),

    path('pending/', views.list_pending, name='pending'),

    path('share/<int:pk>/', views.share, name='sharelink'),
    re_path(r'^share/(?P<token>[0-9A-Za-z_\-:]+)/$', views.view_share_link, name='viewsharelink'),

    path('distribute/<int:pk>/', views.distribute_project, name='distribute'),
    path('progress/<int:pk>/', views.progress_project, name='progress'),

    path('stats/personal/', views.project_stats_personal, name='stats_personal'),
    path('stats/active/', views.project_stats, name='stats'),  # if no kwarg.
    path('stats/<str:status_filter>/', views.project_stats, name='stats'),

]

shen_ring/urls.py
from django.urls import path

from . import views

app_name = 'shen_ring'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('callback/', views.callback, name='callback'),
]

two_factor_custom/urls.py
from django.conf.urls import url
from two_factor.views import (
    BackupTokensView,  PhoneDeleteView, PhoneSetupView,
    ProfileView, QRGeneratorView, SetupCompleteView,
)

from .views import TwoFactorLoginView, TwoFactorDisableView, TwoFactorSetupView

app_name = 'two_factor'

core = [
    url(
        regex=r'^login/$',
        view=TwoFactorLoginView.as_view(),
        name='login',
    ),
    url(
        regex=r'^setup/$',
        view=TwoFactorSetupView.as_view(),
        name='setup',
    ),
    url(
        regex=r'^qrcode/$',
        view=QRGeneratorView.as_view(),
        name='qr',
    ),
    url(
        regex=r'^setup/complete/$',
        view=SetupCompleteView.as_view(),
        name='setup_complete',
    ),
    url(
        regex=r'^backup/tokens/$',
        view=BackupTokensView.as_view(),
        name='backup_tokens',
    ),
    url(
        regex=r'^backup/phone/register/$',
        view=PhoneSetupView.as_view(),
        name='phone_create',
    ),
    url(
        regex=r'^backup/phone/unregister/(?P<pk>\d+)/$',
        view=PhoneDeleteView.as_view(),
        name='phone_delete',
    ),
]

profile = [
    url(
        regex=r'^profile/$',
        view=ProfileView.as_view(),
        name='profile',
    ),
    url(
        regex=r'^disable/$',
        view=TwoFactorDisableView.as_view(),
        name='disable',
    ),
]

urlpatterns = core + profile

templates/templates/index/about.html
{% extends "base.html" %}
{% load static %}
{% block body %}

    <div class="grid">
        <div class="row cells4">
            <div class="cell" style="text-align: center">
                <object data="{% static "img/tuelogo.svg" %}" type="image/svg+xml" style="width:50%;"></object>
                <img src="{% static "img/kolibrilogo.png" %}" alt="Kolibri Solutions Logo" title="Kolibri Solutions Logo">
            </div>
            <div class="cell colspan3">
                <h1>About</h1>
                <p>
                    This website is made by Kolibri Solutions: Frank Boerman and Jeroen van Oorschot.<br />
                    Commissioned by <a href="https://www.tue.nl/en/university/departments/electrical-engineering/"> Department of Electrical Engineering at TU/e</a>
                </p>
                <p><ul>
                    <li><a href="https://kolibrisolutions.nl" title="Kolibri Solutions">Kolibri Solutions</a></li>
                    <li><a href="https://github.com/kolibrisolutions" title="Kolibri Solutions Github"><span class="mif-github"></span> GitHub</a></li>
                </ul>
                </p>
                <p>
                    <a href="http://www.djangoproject.com/">
                        <img src="{% static "img/djangopowered126x54.gif" %}"
                            alt="Powered by Django." title="Powered by Django."/></a>

                </p>
                <div>
                And:
                    <ul>
                        <li><a href="https://jquery.com/" title="jQuery">jQuery</a></li>
                        <li><a href="https://metroui.org.ua/" title="MetroUI CSS">MetroUI CSS</a></li>
                        <li><a href="https://datatables.net/" title="Datatables">Datatables</a></li>
                        <li><a href="https://select2.org" title="Select2">Select2</a></li>
                        <li><a href="https://github.com/avianey/jqDoubleScroll" title="DoubleScroll">DoubleScroll</a></li>
                        <li><a href="http://lokeshdhakar.com/projects/lightbox2/" title="LightBox">LigthBox</a></li>
                        <li><a href="https://github.com/vedmack/yadcf" title="YADCF">Yet Another DataTables Column Filter - (yadcf)</a></li>
                        <li><a href="https://fullcalendar.io/" title="FullCalendar">FullCalendar</a></li>
                        <li><a href="http://www.chartjs.org/">ChartJs</a> </li>
                        <li>..</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/templates/index/feedback_form.html
{% extends 'GenericForm.html' %}

{% block formheader %}
    <p>
    If you have tips how to improve this system, please submit it below. Do not use this form for questions or permission requests.
    For questions please contact the support staff ({{ support_name }})
    </p>
{% endblock %}

templates/templates/index/index.html
{% extends "base.html" %}
{% load index_tags %}
{% load static %}
{% block body %}

    <div class="grid">
        <div class="row cells4">
            <div class="cell" style="text-align: center" id="cellLogos">
                <object data="{% static "img/tuelogo.svg" %}" type="image/svg+xml" style="width:50%;">TU/e Logo</object>
            </div>
            <div class="cell colspan3">
                <h1>Master Project Marketplace</h1>
                <h4>Hello and welcome to the marketplace!</h4>
                {% if user.is_authenticated %}
                    <p>
                        {% if user|has_group:'any' %}
                            As a staff member, you can add or edit projects using the 'projects' menu on top.
                        {% else %}
                            {% if user.registration.exists or not user|is_ele %}
                                Use the 'projects' menu to browse internships and graduation projects.
                            {% else %}
                                Please register your master track and electives using the 'registration' menu on top of
                                the
                                page.
                            {% endif %}
                        {% endif %}
                    </p>
                    <p>If you experience errors or have questions, please contact the EE {{ support_role }}
                        {{ support_name }} at
                        <a href="mailto:{{ support_email }}" title="Mail {{ support_name }}">{{ support_email }}</a>.
                    </p>
                    {% if date_projects %}
                        <br/>
                        <div class="accordion" data-role="accordion" data-close-any="true">
                            <div class="frame active">
                                <div class="heading">Changed projects since your last login</div>
                                <div class="content active bg-lighterGray">
                                    <ul>
                                        {% for date_list in date_projects|slice:'5' %}{# max number of days shown. #}
                                            <li>{{ date_list.0 }}
                                                <ul>
                                                    {% for project in date_list.1 %}
                                                        <li>
                                                            <a href="{% url 'projects:details' project.id %}"
                                                               title="{{ project.Title }}">
                                                                {{ project.Title|truncatewords:'7' }}
                                                            </a>
                                                            by {{ project.ResponsibleStaff.usermeta.get_nice_name }}
                                                        </li>
                                                    {% endfor %}
                                                </ul>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                {% if date_projects|length > 5 %} {# make sure this is the same number as the slice #}
                                    and some more...
                                    {% endif %}
                                </div>
                            </div>
                        </div>

                    {% endif %}
                {% else %}
                    {% csrf_token %}
                    Please start by <a href="{% url 'shen_ring:login' %}" class="button primary">logging in</a><br/>
                    <br/>If you experience problems with logging in, please contact the EE {{ support_role }} for the
                    master,
                    {{ support_name }}.
                {% endif %}

                <br/>
            </div>
        </div>
    </div>
{% endblock %}

templates/templates/index/list_feedback.html
{% extends "base.html" %}
{% block body %}
    <h1>Feedback Reports</h1>
    <table class="table striped hovered datatable">
        <thead>
        <th>TimeStamp</th>
        <th>Reporter</th>
        <th>Url</th>
        <th data-sortable="false">Feedback</th>
        <th>Status</th>
        <th data-searchable="false" data-sortable="false">Actions</th>
        </thead>
        {% for report in feedback_list %}
            <tr>
                <td data-sort="{{ report.Timestamp|date:"U" }}">{{ report.Timestamp }}</td>
                <td>{{ report.Reporter.usermeta.get_nice_name }}</td>
                <td>{{ report.Url }}</td>
                <td>{{ report.Feedback }}</td>
                <td>{{ report.get_Status_display }}</td>
                <td>
                    {% if report.Status != 2 %}
                        <a href="{% url 'index:confirm_feedback' report.id %}">
                            <button class="button info">Confirm</button>
                        </a><br/>
                    {% endif %}
                    <a href="{% url 'index:close_feedback' report.id %}">
                        <button class="button success">Close</button>
                    </a><br/>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
           var dt = $('.datatable').dt_wrapper();
        });
    </script>
{% endblock %}

templates/templates/index/profile.html
{% extends "base.html" %}
{% load index_tags %}
{% block body %}
    <h1>Profile</h1>
    <a href="{% url 'index:changesettings' %}" class="button primary">User Settings</a>
    {% if user.is_superuser %}
        <!-- saml does not support 2fa-->
        <a class="button success" href="{% url 'two_factor:profile' %}">Account Security Settings</a>
    {% endif %}
    {% if user|has_group:"unverified" and not user.is_superuser %}
        <p><strong>
            You have an unverified account.<br/>
            Please contact the support staff or academic advisor to obtain the correct rights.
        </strong></p>
    {% endif %}


    <h4>Personal</h4>
    <table class="table striped">
        <tr>
            <td>Username:</td>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <td>First and last name:</td>
            <td>{{ meta.get_nice_name }}</td>
        </tr>
        <tr>
            <td>Initials</td>
            <td>{{ meta.Initials }}</td>
        </tr>
        <tr>
            <td>Full name</td>
            <td>{{ meta.get_nice_fullname }}</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>{{ user.email }}</td>
        </tr>
    </table>
    <h4>User settings</h4>
    <table class="table striped">
        <tr>
            <td>Suppress action required mails:</td>
            <td><span class="mif-{{ SuppressStatusMails|yesno:"checkmark fg-green,cross fg-red" }}"></span></td>
        </tr>
    </table>

    {% if not student %}
        <h4>Permissions</h4>
        <table class="table striped">
            <tr>
                <td>User can be responsible for a project:</td>
                <td><span class="mif-{{ supervisor|yesno:"checkmark fg-green,cross fg-red" }}"></span></td>
            </tr>
            <tr>
                <td>User can be assistant:</td>
                <td>
                    <span class="mif-{{ assistant|yesno:"checkmark fg-green,cross fg-red" }}"></span>
                </td>
            </tr>
            <tr>
                <td>User is study advisor:</td>
                <td><span class="mif-{{ studyadvisor|yesno:"checkmark fg-green,cross fg-red" }}"></span></td>
            </tr>
            {% if user.is_superuser %}
                <tr>
                    <td>User is God:</td>
                    <td><span class="mif-checkmark fg-green"></span></td>
                </tr>
            {% endif %}
            {% if user.administratoredgroups.exists %}
                <tr>
                    <td>User is administrator of groups:</td>
                    <td>
                        <ul>
                            {% for group in user.administratoredgroups.all %}
                                <li>
                                    {{ group.Group.ShortName }}
                                    ({% if group.Super %}Read and write access{% else %}Read only access{% endif %})
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            {% endif %}
        </table>

    {% else %}

        {#        <h4>Student Information</h4>#}
        {#        <table class="table striped">#}
        {#            <tr>#}
        {#                <td>Department</td>#}
        {#                <td>{{ meta.Department }}</td>#}
        {#            </tr>#}
        {#            <tr>#}
        {#                <td>Study</td>#}
        {#                <td>{{ meta.Study }}</td>#}
        {#            </tr>#}
        {#            <!--<tr>#}
        {#                <td>Cohort</td>#}
        {#                <td>{{ meta.Cohort }}</td>#}
        {#            </tr>#}
        {#            <tr>#}
        {#                <td>Studentnumber</td>#}
        {#                <td>{{ meta.Studentnumber }}</td>#}
        {#            </tr>-->#}
        {#        </table>#}
    {% endif %}
{% endblock %}

templates/templates/index/terms.html
{% extends 'GenericForm.html' %}

{% block body %}
    <h1>Terms of Services</h1>
    <ul>
        {% for term in terms %}
            <li>{{ term.Text }}</li>
        {% endfor %}
    </ul>
    {{ block.super }}
{% endblock %}

templates/templates/index/user_info.html
{% extends "base.html" %}
{% block body %}
    {% if view_user == user %}
        <h1>User info</h1>
        <a href="{% url 'index:profile' %}" class="button primary">User Profile</a>
        <a href="{% url 'index:changesettings' %}" class="button primary">User Settings</a>
    {% else %}
        <h1>Info of {{ view_user.usermeta.get_nice_name }}</h1>
    {% endif %}
    <h2>User</h2>
    <table class="table bordered">
        {% for row in user_model %}
            <tr>
                <td>{{ row.0 }}</td>
                <td>{{ row.1 }}</td>
            </tr>
        {% endfor %}
    </table>
    <h2>User Meta</h2>
    <table class="table bordered">

        {% for row in usermeta_model %}
            <tr>
                <td>{{ row.0 }}</td>
                <td>{{ row.1 }}</td>
            </tr>
        {% endfor %}
    </table>
    <h2>Related models</h2>
    <table class="table bordered">
        {% for row in related %}
            <tr>
                <td>{{ row.0 }}</td>
                <td>
                    <ul>{{ row.1|unordered_list }}</ul>
                </td>
            </tr>
        {% endfor %}
    </table>
    {#    <h2>Distribution related models</h2>#}
    {#    <table class="table bordered">#}
    {#        {% for row in distribution %}#}
    {#            <tr>#}
    {#                <td>{{ row.0 }}</td>#}
    {#                <td>#}
    {#                    <ul>{{ row.1|unordered_list }}</ul>#}
    {#                </td>#}
    {#            </tr>#}
    {#        {% endfor %}#}
    </table>
    <h2>Info as JSON:</h2>
    <textarea title="json">
        {{ json }}
    </textarea>
{% endblock %}