MasterMarketplace/urls.py
"""
MasterMarketplace URL Configuration

"""
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    # path('osiris/', include('osiris.urls')),
    path('', include('index.urls')),
    path('accesscontrol/', include('accesscontrol.urls')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/', include('api.urls')),
    path('download/', include('download.urls')),
    path('godpowers/', include('godpowers.urls')),
    path('impersonate/', include('impersonate.urls')),
    path('js_error_hook/', include('django_js_error_hook.urls')),
    path('projects/', include('projects.urls')),
    path('registration/', include('registration.urls')),
    path('students/', include('students.urls')),
    path('studyguide/', include('studyguide.urls')),
    path('support/', include('support.urls')),
    path('tracking/', include('tracking.urls')),
    path('two_factor/', include('two_factor_custom.urls')),
    path('shen/', include('shen_ring.urls')),

]

if settings.DEBUG and False:
    import debug_toolbar

    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),

    ] + urlpatterns

# static download path, for unprotected downloads. Not used.
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers.
handler400 = 'index.views.error400'
handler404 = 'index.views.error404'
handler403 = 'index.views.error403'
handler500 = 'index.views.error500'

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.api_info, name='api'),

    # path('status/upgrade/<int:pk>/', views.upgrade_status_api, name='upgradestatus'),
    # path('status/downgrade/<int:pk>/', views.downgrade_status_api, name='downgradestatus'),
    # path('getgroupadmins/', views.get_group_admins, name='getgroupadmins'),
    # path('getgroupadmins/<str:group>/', views.get_group_admins, name='getgroupadminsarg'),
    path('projects/', views.list_published_api, name='listpublished'),
    path('projects/group/', views.list_public_projects_api, name='listpublishedpergroup'),
    path('projects/titles/', views.list_public_projects_titles_api, name='listpublishedtitles'),
    path('projects/<int:pk>/', views.detail_proposal_api, name='getpublisheddetail'),
    path('getgroupadmins/<slug:type>/', views.get_group_admins, name='getgroupadmins'),
    path('getgroupadmins/<slug:type>/<int:pk>/', views.get_group_admins, name='getgroupadmins'),
    path('verify/assistant/<int:pk>/', views.verify_assistant, name='verifyassistant'),

]

download/urls.py
from django.urls import path, re_path
from django.conf import settings
from . import views

# define all kinds of file downloads here.
# Files can be downloaded using their filename (for backward compatibility with file edit) or using their object ID
app_name = 'download'

reguuid = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.[A-z]{1,5}"  # regex for uuid with extension

urlpatterns = [
    # public files
    # url(r'publicfile/(?P<fileid>[0-9]+)$', views.PublicFiles, name='publicfile'),

    # markdown images
    re_path(settings.MARKDOWN_IMAGE_UPLOAD_FOLDER+'/(?P<file_name>' + reguuid + ')$', views.markdown_file_download, name='markdown_file'),

    # proposal attachments
    path('projectfile/<str:ty>/<int:fileid>', views.project_files, name='projectfile'),
    re_path(r'project_(?P<project_id>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.project_files, name='project_files'),
    # direct url

    # promotion logos
    path('promotionfile/<int:fileid>', views.promotion_files, name='promotionfile'),
    re_path(r'promotion/(?P<fileid>' + reguuid + ')$', views.promotion_files, name='promotion_files'),  # direct url


    # student files (professionalskills)
    path('studentfile/<int:fileid>', views.student_files, name='studentfile'),  # object-id
    re_path(r'dist_(?P<distid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.student_files, name='student_files'),  # uri

    # capacity group images.
    path('capacitygroupimage/<int:fileid>', views.capacity_group_images, name='capacitygroupimage'),  # object-id
    re_path(r'capacitygroup_(?P<capid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.capacity_group_images, name='capacitygroupimages'),  # uri

    # capacity group images.
    path('masterprogramimage/<int:fileid>', views.master_program_images, name='masterprogramimage'),  # object-id
    re_path(r'masterprogram_(?P<capid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.master_program_images, name='masterprogramimages'),  # uri
]

studyguide/urls.py
from django.urls import path

from . import views

app_name = 'studyguide'
urlpatterns = [
    path('courses/list/', views.list_courses, name='courseslist'),
    path('years/', views.list_years, name='yearslist'),
    path('courses/list/<int:year>/', views.list_courses, name='courseslist'),

    path('masterprogram/add/', views.add_master_program, name='addmasterprogram'),
    path('masterprogram/edit/<int:pk>/', views.edit_master_program, name='editmasterprogram'),
    path('masterprogram/delete/<int:pk>/', views.delete_master_program, name='deletemasterprogram'),
    path('masterprogram/list/', views.list_master_programs, name='masterprogramlist'),
    path('masterprogram/list/<int:year>/', views.list_master_programs, name='masterprogramlist'),
    path('masterprogram/detail/<int:pk>/', views.detail_master_program, name='detailmasterprogram'),
    path('masterprogram/images/<int:pk>/', views.edit_master_program_images, name='editmasterprogramimages'),
    path('masterprogram/images/<int:pk>/add/', views.add_master_program_image, name='addmasterprogramimage'),

    # new naming for masterprogram
    path('path/add/', views.add_master_program, name='addpath'),
    path('path/edit/<int:pk>/', views.edit_master_program, name='editpath'),
    path('path/delete/<int:pk>/', views.delete_master_program, name='deletepath'),
    path('path/list/', views.list_master_programs, name='pathslist'),
    path('path/list/<int:year>/', views.list_master_programs, name='pathslist'),
    path('path/detail/<int:pk>/', views.detail_master_program, name='detailpath'),

    path('capacitygroup/add/', views.add_capacity_group, name='addcapacitygroup'),
    path('capacitygroup/edit/<int:pk>/', views.edit_capacity_group, name='editcapacitygroup'),
    path('capacitygroup/delete/<int:pk>/', views.delete_capacity_group, name='deletecapacitygroup'),
    path('capacitygroup/detail/<int:pk>/', views.detail_capacity_group, name='detailcapacitygroup'),
    path('capacitygroup/detail/<str:shortname>/', views.detail_capacity_group_name, name='detailcapacitygroup'),
    path('capacitygroup/list/', views.list_capacity_groups, name='listcapacitygroups'),
    path('capacitygroup/images/<int:pk>/', views.edit_capacity_group_images, name='editcapacitygroupimages'),
    path('capacitygroup/images/<int:pk>/add/', views.add_capacity_group_images, name='addcapacitygroupimage'),

    path('admin/course/create/', views.main_course_form_view, name='maincourseadd'),
    path('admin/course/edit/<slug:code>/<int:year>/', views.main_course_form_view, name='maincourseedit'),
    path('admin/course/delete/<slug:code>/<int:year>/', views.delete_main_course, name='maincoursedelete'),

]

studyguide/views.py
import logging

from django.forms import modelformset_factory
from django.shortcuts import render, get_object_or_404

from general_form import ConfirmForm
from general_model import delete_object
from index.decorators import group_required, cache_for_students, cache_for_anonymous
from registration.CourseBrowser import CourseBrowser
from timeline.models import Year
from timeline.utils import get_year
from .forms import MasterProgramForm, CapacityGroupForm, MainCourseForm, CapacityGroupImageForm, MasterProgramImageForm
from .models import MasterProgram, CapacityGroup, MainCourse, CourseType, CapacityGroupImage, MasterProgramImage

logger = logging.getLogger('django')


@cache_for_students
@cache_for_anonymous
def list_years(request):
    """

    :param request:
    :return:
    """
    years = Year.objects.all()
    return render(request, 'studyguide/list_years.html', {
        'years': years,
    })


@cache_for_students
@cache_for_anonymous
def list_courses(request, year=None):
    """
    List courses

    :param request:
    :param year: pk of the year to filter on. Year to filter. 0 for all
    :return:
    """
    if year is None:  # get current year, no year supplied
        year = get_year()
    else:
        year = get_object_or_404(Year, pk=year)

    api = CourseBrowser(year=year.Begin.year)
    courses_per_type = {}
    for type in CourseType.objects.all():
        codes = [c.Code for c in type.courses.filter(Year=year)]
        courses = [item for sublist in api.get_list_courses_data(codes) for item in sublist]
        courses_per_type[str(type)] = courses

    return render(request, 'studyguide/list_courses.html', {
        'courses_per_type': courses_per_type,
        'year': year,
        'hide_sidebar': True
    })


@cache_for_students
@cache_for_anonymous
def list_master_programs(request, year=None):
    """
    List specialization paths

    :param request:
    :param year: Year to filter. 0 for all, None for current
    :return:
    """
    paths = MasterProgram.objects.all().prefetch_related('MainCourses', 'Group')
    if year is None:  # get current year, no year supplied
        year = get_year()
        paths = paths.filter(Year=year)
    elif year != 0:  # get specified year
        year = get_object_or_404(Year, pk=year)
        paths = paths.filter(Year=year)
    return render(request, 'studyguide/list_masterprograms.html', {
        'programs': paths,
        'year': year,
        'hide_sidebar': True,
    })


@cache_for_students
@cache_for_anonymous
def detail_master_program(request, pk):
    obj = get_object_or_404(MasterProgram, pk=pk)
    return render(request, 'studyguide/detail_masterprogram.html', {
        'program': obj
    })


@group_required('studyadvisors', 'directors')
def edit_master_program_images(request, pk):
    """
    Edit master_program images. Only for supportstaff
    These files are shown on the master program detail page.

    :param request:
    :param pk: pk of master program
    """
    mp = get_object_or_404(MasterProgram, pk=pk)
    form_set = modelformset_factory(MasterProgramImage, form=MasterProgramImageForm, can_delete=True, extra=0)
    qu = MasterProgramImage.objects.filter(MasterProgram=mp)
    formset = form_set(queryset=qu)

    if request.method == 'POST':
        formset = form_set(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            return render(request, "base.html", {"Message": "File changes saved!", "return": "studyguide:detailmasterprogram", 'returnget': mp.pk})
    return render(request, 'GenericForm.html',
                  {'formset': formset, 'formtitle': 'All images of {}'.format(mp), 'buttontext': 'Save changes'})


@group_required('studyadvisors', 'directors')
def add_master_program_image(request, pk):
    """
    Add a image to master program

    :param request:
    :param pk: pk of the master program
    :return:
    """
    obj = get_object_or_404(MasterProgram, pk=pk)
    form = MasterProgramImageForm
    if request.method == 'POST':
        form = form(request.POST, request.FILES, request=request)
        if form.is_valid():
            file = form.save(commit=False)
            file.MasterProgram = obj
            file.save()
            return render(request, "base.html",
                          {"Message": "File saved!",
                           "return": 'studyguide:detailmasterprogram', 'returnget': obj.pk})

    return render(request, 'GenericForm.html',
                  {'form': form, 'formtitle': 'Add image to master program {}'.format(obj), 'buttontext': 'Save'})


@cache_for_students
@cache_for_anonymous
def list_capacity_groups(request):
    """
    List all capacity groups, edit buttons for support staff

    :param request:
    :return:
    """
    return render(request, 'studyguide/list_capacitygroups.html', {
        'groups': CapacityGroup.objects.all().select_related('Head'),
        'hide_sidebar': True
    })


@cache_for_students
@cache_for_anonymous
def detail_capacity_group(request, pk):
    group = get_object_or_404(CapacityGroup, pk=pk)
    return render(request, 'studyguide/detail_capacitygroup.html', {
        'group': group
    })


@cache_for_students
@cache_for_anonymous
def detail_capacity_group_name(request, shortname):
    group = get_object_or_404(CapacityGroup, ShortName=shortname)
    return render(request, 'studyguide/detail_capacitygroup.html', {
        'group': group
    })


@group_required('studyadvisors', 'directors')
def add_capacity_group(request):
    if request.method == 'POST':
        form = CapacityGroupForm(request.POST)
        if form.is_valid():
            obj = form.save()
            return render(request, 'base.html', {
                'Message': 'Capacity group {} added.'.format(obj.FullName),
                'return': 'studyguide:listcapacitygroups'
            })
    else:
        form = CapacityGroupForm()
    return render(request, 'GenericForm.html', {
        'form': form,
        'formtitle': 'Add New Capacity Group',
        'buttontext': 'Add',
        'upload_image': True,

    })


@group_required('studyadvisors', 'directors')
def edit_capacity_group(request, pk):
    obj = get_object_or_404(CapacityGroup, pk=pk)

    if request.method == "POST":
        form = CapacityGroupForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return render(request, 'base.html', {
                'Message': 'Group {} saved.'.format(obj),
                'return': 'studyguide:listcapacitygroups',
            })
    else:
        form = CapacityGroupForm(instance=obj)

    return render(request, 'GenericForm.html', {
        'form': form,
        'formtitle': 'Edit Group',
        'buttontext': 'Save',
        'upload_image': True,
    })


@group_required('studyadvisors', 'directors')
def delete_capacity_group(request, pk):
    obj = get_object_or_404(CapacityGroup, pk=pk)
    if request.method == 'POST':
        form = ConfirmForm(request.POST)
        if form.is_valid():
            delete_object(obj)
            return render(request, 'base.html', {
                'Message': 'Capacity group {} deleted.'.format(obj),
                'return': 'studyguide:listcapacitygroups'
            })
    else:
        form = ConfirmForm()
    return render(request, 'GenericForm.html', {
        'form': form,
        'formtitle': 'Confirm deletion of {}'.format(obj),
        'buttontext': 'Delete'
    })


@group_required('studyadvisors', 'directors')
def edit_capacity_group_images(request, pk):
    """
    Edit cap group files. Only for supportstaff
    These files are shown on the capacitygroup detail page.

    :param request:
    """
    cg = get_object_or_404(CapacityGroup, pk=pk)
    form_set = modelformset_factory(CapacityGroupImage, form=CapacityGroupImageForm, can_delete=True, extra=0)
    qu = CapacityGroupImage.objects.filter(CapacityGroup=cg)
    formset = form_set(queryset=qu)

    if request.method == 'POST':
        formset = form_set(request.POST, request.FILES)
        if formset.is_valid():
            formset.save()
            return render(request, "base.html", {"Message": "File changes saved!", "return": "studyguide:detailcapacitygroup", 'returnget': cg.pk})
    return render(request, 'GenericForm.html',
                  {'formset': formset, 'formtitle': 'All images of {}'.format(cg.ShortName), 'buttontext': 'Save changes'})


@group_required('studyadvisors', 'directors')
def add_capacity_group_images(request, pk):
    """
    Add a image to capacity group

    :param request:
    :param pk: pk of the group
    :return:
    """
    obj = get_object_or_404(CapacityGroup, pk=pk)
    form = CapacityGroupImageForm
    if request.method == 'POST':
        form = form(request.POST, request.FILES, request=request)
        if form.is_valid():
            file = form.save(commit=False)
            file.CapacityGroup = obj
            file.save()
            return render(request, "base.html",
                          {"Message": "File saved!",
                           "return": 'studyguide:detailcapacitygroup', 'returnget': obj.pk})

    return render(request, 'GenericForm.html',
                  {'form': form, 'formtitle': 'Add image to capacity group {}'.format(obj.ShortName), 'buttontext': 'Save'})


@group_required('studyadvisors', 'directors')
def add_master_program(request):
    if request.method == 'POST':
        form = MasterProgramForm(request.POST)
        if form.is_valid():
            program = form.save()
            return render(request, 'base.html', {
                'Message': 'Program {} added.'.format(program),

templates/templates/studyguide/detail_capacitygroup.html
{% extends 'base.html' %}
{% load static %}
{% load index_tags %}

{% block body %}
    <h1>{{ group.FullName }} ({{ group.ShortName }})</h1>
    <h4>{{ group.Head.usermeta.get_nice_name }}</h4>
    {% if group.programs.exists %}
        <h4>Specialization paths:</h4>
        <ul>
            {% for path in group.programs.all %}
                <li>
                    <a href="{% url 'studyguide:detailmasterprogram' path.pk %}">{{ path }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if group.images.all|length > 0 %}
        <div id="imageCarousel" class="carousel" data-role="carousel" data-height="300"
             data-controls="true" data-markers="false" data-auto="false">
            {% for image in group.images.all %}
                <div class="slide">
                    <a href="{% url "download:capacitygroupimage" image.pk %}" data-lightbox="lightbox1"
                       data-title="{{ image.Caption }}">
                        <img data-role="fitImage" data-format="fill"
                             src="{% url "download:capacitygroupimage" image.pk %}"
                             alt="{{ image.Caption }}"
                             referrerpolicy="no-referrer-when-downgrade"
                        />
                    </a>
                    <div class="imageCaption">
                        <h5>{{ image.Caption }}</h5>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div id="imageCarousel_thumbs" class="padding10 bg-grayLighter align-center">
            {% for image in group.images.all %}
                <div class="thumb" data-index="{{ forloop.counter }}"><img
                        src="{% url "download:capacitygroupimage" image.pk %}"
                        data-role="fitImage"
                        data-format="fill"
                        alt="{{ image.Caption }}"
                        referrerpolicy="no-referrer-when-downgrade">
                </div>
            {% endfor %}
        </div>

    {% endif %}


    <p>
        {{ group.Info|show_markdown_restricted }}
    </p>


    {% if user|has_group:"studyadvisors" %}
        <a href="{% url 'studyguide:editcapacitygroup'  group.pk %}" class="button primary rounded">Edit</a>
        <a href="{% url 'studyguide:editcapacitygroupimages'  group.pk %}" class="button primary rounded">Edit Images</a>
        <a href="{% url 'studyguide:addcapacitygroupimage'  group.pk %}" class="button primary rounded">Add Image</a>
    {% endif %}
{% endblock %}

{% block stylesheets %}
    <link href="{% static "css/lightbox.css" %}" rel="stylesheet">
    <style>
        .thumb {
            background: white;
            padding: 4px;
            display: inline-block;
            height: 2.375rem;
            width: 2.375rem;
            border: 1px transparent solid;
            cursor: pointer;
        }

        #imageCarousel, #imageCarousel_thumbs {
            max-width: 600px;
        }

        .imageCaption {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background-color: rgba(58, 58, 58, .8);
            color: white;
            padding: 5px;
        }
    </style>
{% endblock %}
{% block scripts %}

    {{ block.super }}
    <script src="{% static "js/lightbox.js" %}"></script>
    <script>
        $(document).ready(function () {
            {% if group.images.all|length > 1 %}
                var icar = $('#imageCarousel').data('carousel');
                var thumbs = $('#imageCarousel_thumbs > .thumb');
                $.each(thumbs, function () {
                    var thumb = $(this), index = thumb.data('index') - 1;
                    thumb.on('click', function () {
                        icar.slideTo(index);
                    });
                });
            {% endif %}

        });
    </script>


{% endblock %}

templates/templates/studyguide/detail_masterprogram.html
{% extends 'base.html' %}
{% load static %}
{% load index_tags %}

{% block body %}
    <a href="{% url 'studyguide:masterprogramlist' %}" class="button primary">Path List</a>
    <h1>{{ program.Name }} in {{ program.Year }}</h1>
    <table class="table">
        <tr>
            <td>Group:</td>
            <td>
                {% if program.Group.count == 1 %}
                    <a href="{% url 'studyguide:detailcapacitygroup' program.Group.all.0.pk %}">{{ program.Group.all.0 }}</a>
                {% else %}
                    <ul>
                        {% for group in program.Group.all %}
                            <li>
                                <a href="{% url 'studyguide:detailcapacitygroup' group.pk %}">{{ group }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>Courses:</td>
            <td>
                <ul>
                    {% for course in program.MainCourses.all %}
                        <li>
                            {% if course.Info %}
                                    <a href="{{ course.Info.detaillink }}"> {# Course.Info is a function to CourseBrowser to get Osirislink #}
                                        {{ course.Code }} - {{ course.Info.name }}
                                    </a>
                                {% else %}
                                    {{ course.Code }}
                                {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </td>
        </tr>
        <tr>
            <td>External Link:</td>
            <td>
                {% if program.DetailLink %}
                    <a href="{{ program.DetailLink }}" class="button info rounded">Info</a>
                {% else %}
                    Not available
                {% endif %}
            </td>
        </tr>
    </table>


    {% if program.images.all|length > 0 %}
        <div id="imageCarousel" class="carousel" data-role="carousel" data-height="300"
             data-controls="true" data-markers="false" data-auto="false">
            {% for image in program.images.all %}
                <div class="slide">
                    <a href="{% url "download:masterprogramimage" image.pk %}" data-lightbox="lightbox1"
                       data-title="{{ image.Caption }}">
                        <img data-role="fitImage" data-format="fill"
                             src="{% url "download:masterprogramimage" image.pk %}"
                             alt="{{ image.Caption }}"
                             referrerpolicy="no-referrer-when-downgrade"
                        />
                    </a>
                    <div class="imageCaption">
                        <h5>{{ image.Caption }}</h5>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div id="imageCarousel_thumbs" class="padding10 bg-grayLighter align-center">
            {% for image in program.images.all %}
                <div class="thumb" data-index="{{ forloop.counter }}"><img
                        src="{% url "download:masterprogramimage" image.pk %}"
                        data-role="fitImage"
                        data-format="fill"
                        alt="{{ image.Caption }}"
                        referrerpolicy="no-referrer-when-downgrade">
                </div>
            {% endfor %}
        </div>

    {% endif %}


    <p>
        {{ program.Info|show_markdown_restricted }}
    </p>

    {% if user|has_group:"studyadvisors" %}
        <a href="{% url 'studyguide:editmasterprogram' program.id %}" class="button primary rounded">Edit</a>
        <a href="{% url 'studyguide:deletemasterprogram' program.id %}" class="button danger rounded">Delete</a>
        <a href="{% url 'studyguide:editmasterprogramimages'  program.pk %}" class="button primary rounded">Edit Images</a>
        <a href="{% url 'studyguide:addmasterprogramimage'  program.pk %}" class="button primary rounded">Add Image</a>
    {% endif %}
{% endblock %}

{% block stylesheets %}
    <link href="{% static "css/lightbox.css" %}" rel="stylesheet">
    <style>
        .thumb {
            background: white;
            padding: 4px;
            display: inline-block;
            height: 2.375rem;
            width: 2.375rem;
            border: 1px transparent solid;
            cursor: pointer;
        }

        #imageCarousel, #imageCarousel_thumbs {
            max-width: 600px;
        }

        .imageCaption {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            background-color: rgba(58, 58, 58, .8);
            color: white;
            padding: 5px;
        }
    </style>
{% endblock %}
{% block scripts %}

    {{ block.super }}
    <script src="{% static "js/lightbox.js" %}"></script>
    <script>
        $(document).ready(function () {
            {% if program.images.all|length > 1 %}
                var icar = $('#imageCarousel').data('carousel');
                var thumbs = $('#imageCarousel_thumbs > .thumb');
                $.each(thumbs, function () {
                    var thumb = $(this), index = thumb.data('index') - 1;
                    thumb.on('click', function () {
                        icar.slideTo(index);
                    });
                });
            {% endif %}

        });
    </script>


{% endblock %}

templates/templates/studyguide/list_courses.html
{% extends "base.html" %}
{% load custom_filters %}
{% load index_tags %}

{% block body %}
    {% if not administration %}
        <h1>Courses List</h1>
    {% else %}
        <h1>Administration Codes List</h1>
    {% endif %}
    {% if year %}
        Showing courses of {{ year }}.
    {% else %}
        Showing courses of all years in the system.
    {% endif %}
    &nbsp
    <a href="{% url 'studyguide:yearslist' %}" class="button primary">Change years</a>
    {% if user|has_group:"studyadvisors" %}
    <a href="{% url 'studyguide:maincourseadd' %}" class="button">Add Course</a>
    {% endif %}
    <br/>
    <table class="table bordered striped hovered datatable">
        <thead>
        <tr>
            <th>Code</th>
            <th>Name</th>
            <th>Type</th>
            <th>Group</th>
            <th>Quarter</th>
            <th>Time slot</th>
            <th>Teacher</th>
            <th data-searchable="false" data-sortable="false">Osiris</th>
            {% if user|has_group:"studyadvisors" %}
                <th data-searchable="false" data-sortable="false">Actions</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for type, courses in courses_per_type.items %}
            {% for course in courses %}
                <tr>
                    <td><b>{{ course.code }}</b></td>
                    <td>{{ course.name }}</td>
                    <td>{{ type }}</td>
                    <td>{{ course.owner.group }}</td>
                    <td>{{ course.quartile }}</td>
                    <td>{{ course.timeslot }}</td>
                    <td>{{ course.responsiblestaff.name }}</td>
                    <td><a href="{{ course.detaillink }}" class="button info rounded">Osiris</a></td>
                    {% if user|has_group:"studyadvisors" %}
                    <td>
                        <a href="{% url 'studyguide:maincourseedit' course.code year.Begin.year %}" class="button primary">Edit</a>
                        <a href="{% url 'studyguide:maincoursedelete' course.code year.Begin.year %}" class="button warning">Delete</a>
                    </td>
                    {% endif %}
                </tr>
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            $('.datatable').dt_wrapper([
                    {column_number: 0, filter_type: 'text'}, //code
                    {column_number: 1, filter_type: 'text'}, //name
                    {column_number: 2, filter_type: 'select'}, //type
                    {column_number: 3, filter_type: 'select'}, //Group
                    {column_number: 4, filter_type: "multi_select", filter_match_mode: 'exact'}, // Quarter
                    {column_number: 5, filter_type: "multi_select", filter_match_mode: 'exact'}, //timeslot
                    {column_number: 6, filter_type: "select"}, //teacher
                ]
            );
        });
    </script>
{% endblock %}

templates/templates/studyguide/list_years.html
{% extends "base.html" %}
{% load custom_filters %}

{% block body %}
    <h1>Years list</h1>
    <br/>
    <table class="table bordered striped hovered">
        <thead>
        <tr>
            <th>Year</th>
            <th>Courses</th>
        </tr>
        </thead>
        <tbody>
        {% for year in years %}
            <tr>
                <td>{{ year.Name }}</td>
                <td>
                    <a href="{% url 'studyguide:courseslist' year.pk %}" class="button primary">List Courses</a>
                    <a href="{% url 'studyguide:pathslist' year.pk %}" class="button primary">List Specialization
                        Paths</a>
                    {% if user.is_superuser %}
                        <a href="{% url 'admin:timeline_year_change' year.pk %}" class="button warning">Admin edit</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}