MasterMarketplace/urls.py
"""
MasterMarketplace URL Configuration

"""
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    # path('osiris/', include('osiris.urls')),
    path('', include('index.urls')),
    path('accesscontrol/', include('accesscontrol.urls')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/', include('api.urls')),
    path('download/', include('download.urls')),
    path('godpowers/', include('godpowers.urls')),
    path('impersonate/', include('impersonate.urls')),
    path('js_error_hook/', include('django_js_error_hook.urls')),
    path('projects/', include('projects.urls')),
    path('registration/', include('registration.urls')),
    path('students/', include('students.urls')),
    path('studyguide/', include('studyguide.urls')),
    path('support/', include('support.urls')),
    path('tracking/', include('tracking.urls')),
    path('two_factor/', include('two_factor_custom.urls')),
    path('shen/', include('shen_ring.urls')),

]

if settings.DEBUG and False:
    import debug_toolbar

    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),

    ] + urlpatterns

# static download path, for unprotected downloads. Not used.
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers.
handler400 = 'index.views.error400'
handler404 = 'index.views.error404'
handler403 = 'index.views.error403'
handler500 = 'index.views.error500'

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.api_info, name='api'),

    # path('status/upgrade/<int:pk>/', views.upgrade_status_api, name='upgradestatus'),
    # path('status/downgrade/<int:pk>/', views.downgrade_status_api, name='downgradestatus'),
    # path('getgroupadmins/', views.get_group_admins, name='getgroupadmins'),
    # path('getgroupadmins/<str:group>/', views.get_group_admins, name='getgroupadminsarg'),
    path('projects/', views.list_published_api, name='listpublished'),
    path('projects/group/', views.list_public_projects_api, name='listpublishedpergroup'),
    path('projects/titles/', views.list_public_projects_titles_api, name='listpublishedtitles'),
    path('projects/<int:pk>/', views.detail_proposal_api, name='getpublisheddetail'),
    path('getgroupadmins/<slug:type>/', views.get_group_admins, name='getgroupadmins'),
    path('getgroupadmins/<slug:type>/<int:pk>/', views.get_group_admins, name='getgroupadmins'),
    path('verify/assistant/<int:pk>/', views.verify_assistant, name='verifyassistant'),

]

download/urls.py
from django.urls import path, re_path
from django.conf import settings
from . import views

# define all kinds of file downloads here.
# Files can be downloaded using their filename (for backward compatibility with file edit) or using their object ID
app_name = 'download'

reguuid = "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.[A-z]{1,5}"  # regex for uuid with extension

urlpatterns = [
    # public files
    # url(r'publicfile/(?P<fileid>[0-9]+)$', views.PublicFiles, name='publicfile'),

    # markdown images
    re_path(settings.MARKDOWN_IMAGE_UPLOAD_FOLDER+'/(?P<file_name>' + reguuid + ')$', views.markdown_file_download, name='markdown_file'),

    # proposal attachments
    path('projectfile/<str:ty>/<int:fileid>', views.project_files, name='projectfile'),
    re_path(r'project_(?P<project_id>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.project_files, name='project_files'),
    # direct url

    # promotion logos
    path('promotionfile/<int:fileid>', views.promotion_files, name='promotionfile'),
    re_path(r'promotion/(?P<fileid>' + reguuid + ')$', views.promotion_files, name='promotion_files'),  # direct url


    # student files (professionalskills)
    path('studentfile/<int:fileid>', views.student_files, name='studentfile'),  # object-id
    re_path(r'dist_(?P<distid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.student_files, name='student_files'),  # uri

    # capacity group images.
    path('capacitygroupimage/<int:fileid>', views.capacity_group_images, name='capacitygroupimage'),  # object-id
    re_path(r'capacitygroup_(?P<capid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.capacity_group_images, name='capacitygroupimages'),  # uri

    # capacity group images.
    path('masterprogramimage/<int:fileid>', views.master_program_images, name='masterprogramimage'),  # object-id
    re_path(r'masterprogram_(?P<capid>[0-9]+)/(?P<fileid>' + reguuid + ')$', views.master_program_images, name='masterprogramimages'),  # uri
]

projects/urls.py
from django.urls import path, re_path

from . import views

app_name = 'projects'

urlpatterns = [
    path('list/', views.list_public_projects, name='list'),
    path('favorites/', views.list_favorite_projects, name='favorites'),

    path('list/<str:type_filter>/', views.list_public_projects, name='list'),
    path('favorites/<str:type_filter>/', views.list_favorite_projects, name='favorites'),

    path('group/active/', views.list_group_projects, name='listgroupprojects'),
    path('group/<str:status_filter>/', views.list_group_projects, name='listgroupprojects'),

    path('details/<int:pk>/', views.detail_project, name='details'),
    path('create/', views.create_project, name='create'),
    path('own/active/', views.list_own_projects, name='chooseedit'),  # for if no kwargs given, default to active.
    path('own/<str:status_filter>/', views.list_own_projects, name='chooseedit'),
    path('edit/<int:pk>/', views.edit_project, name='edit'),
    path('copy/<int:pk>/', views.copy_project, name='copy'),

    path('files/add/<str:ty>/<int:pk>/', views.add_file, name='addfile'),
    path('files/edit/<str:ty>/<int:pk>/', views.edit_file, name='editfile'),

    path('delete/ask/<int:pk>/', views.ask_delete_project, name='askdeleteproject'),
    path('delete/<int:pk>/', views.delete_project, name='deleteproject'),

    path('labels/', views.list_labels, name='labels'),
    path('labels/add/', views.add_label, name='createlabel'),
    path('labels/<int:pk>/', views.edit_label, name='editlabel'),
    path('labels/activate/<int:pk>/', views.activate_label, name='activatelabel'),
    path('labels/delete/<int:pk>/', views.delete_label, name='deletelabel'),

    path('status/upgrade/<int:pk>/', views.upgrade_status, name='upgradestatus'),
    path('status/downgrade/<int:pk>/', views.downgrade_status, name='downgradestatusmessage'),

    # cpv
    path('contentpolicy/', views.content_policy_view, name='contentpolicy'),
    path('contentpolicy/calc/', views.content_policy_calc, name='contentpolicycalc'),

    path('pending/', views.list_pending, name='pending'),

    path('share/<int:pk>/', views.share, name='sharelink'),
    re_path(r'^share/(?P<token>[0-9A-Za-z_\-:]+)/$', views.view_share_link, name='viewsharelink'),

    path('distribute/<int:pk>/', views.distribute_project, name='distribute'),
    path('progress/<int:pk>/', views.progress_project, name='progress'),

    path('stats/personal/', views.project_stats_personal, name='stats_personal'),
    path('stats/active/', views.project_stats, name='stats'),  # if no kwarg.
    path('stats/<str:status_filter>/', views.project_stats, name='stats'),

]

students/urls.py
from django.urls import path

from . import views

app_name = 'students'
urlpatterns = [
    path('applications/', views.list_applications, name='list_applications'),

    path('apply/<int:pk>/', views.apply, name='apply'),
    path('application/confirm/<int:pk>/', views.confirm_apply, name='confirmapply'),

    path('application/retract/<int:application_id>/', views.retract_application, name='retractapplication'),
    path('files/<int:dist>/', views.list_files, name='files'),
    path('files/<int:dist>/add/', views.add_file, name='addfile'),
    path('files/<int:dist>/edit/<int:file>/', views.edit_file, name='editfile'),
    # path('files/delete/<int:file>/', views.delete_file, name='deletefile'),
]

students/forms.py
from django.forms import ValidationError

from general_form import clean_file_default, FileForm
from general_model import get_ext, print_list
from templates import widgets
from .models import FileExtension, StudentFile


def clean_studentfile_default(self):
    """
    Clean function for studentfile form. Checks if the extension is in the allowed extensions for this type file.

    :param self:
    :return:
    """
    file = clean_file_default(self)
    if get_ext(file.name) not in FileExtension.objects.all().values_list('Name', flat=True):
        raise ValidationError('This file extension is not allowed. Allowed extensions: '
                              + print_list(FileExtension.objects.all()))
    return file


class StudentFileForm(FileForm):
    """
    Upload or edit a studentfile
    """

    class Meta(FileForm.Meta):
        model = StudentFile
        fields = ['File', 'Caption']
        widgets = {
            'File': widgets.MetroFileInput,
            'Caption': widgets.MetroTextInput,
            # 'Type': widgets.MetroSelect
        }

    def clean_File(self):
        return clean_studentfile_default(self)

students/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from projects.decorators import can_view_project
from students.decorators import can_apply
from index.decorators import student_only
from projects.models import Project
from tracking.models import ApplicationTracking
from .forms import StudentFileForm
from .models import Application, Distribution, StudentFile
from general_view import get_grouptype

@student_only()
def list_applications(request):
    """
    List the applications of a student, with a button to retract the application
    Also lists distributions.

    :param request:
    """
    projs = Project.objects.filter(Q(applications__Student=request.user) | Q(distributions__Student=request.user)).distinct()
    projlist = []
    for proj in projs:
        try:
            a = proj.applications.get(Student=request.user)
        except Application.DoesNotExist:
            a = None
        try:
            d = proj.distributions.get(Student=request.user)
        except Distribution.DoesNotExist:
            d = None
        x = {'project': proj, 'application': a, 'distribution': d}
        projlist.append(x)

    return render(request, "students/list_applications.html", context={
        'projlist': projlist
    })


@student_only()
def retract_application(request, application_id):
    """
    Let a user un-apply / retract an application.

    :param request:
    :param application_id: Application id
    """
    appl = get_object_or_404(Application, pk=application_id)
    if appl.Project.distributions.filter(Student=request.user).exists():
        raise PermissionDenied("You cannot retract this application, because you are distributed to this project. If this distribution is incorrect, please contact the responsible staff member of the project.")

    track = ApplicationTracking()
    track.Project = appl.Project
    track.Student = request.user
    track.Type = 'r'
    track.save()

    appl.delete()
    return render(request, "base.html", context={
        "Message": "Deleted application",
        "return": 'students:list_applications',
    })


@can_view_project
@can_apply
def apply(request, pk):
    """
    Let a user apply to a project. Called after confirmapply.

    :param request:
    :param pk: id of a project.
    """
    prop = get_object_or_404(Project, pk=pk)
    if request.user.applications.count() >= settings.MAX_NUM_APPLICATIONS:
        return render(request, "base.html", context={
            "Message": "already at max amount of applied projects<br>"
                       "retract one first before continuing",
            "return": 'students:list_applications',
        })
    if Application.objects.filter(Q(Project=prop) & Q(Student=request.user)).exists():
        return render(request, "base.html", context={
            "Message": "You already applied to this project.",
            "return": 'students:list_applications',
        })

    track = ApplicationTracking()
    track.Project = prop
    track.Student = request.user
    track.Type = 'a'
    track.save()

    appl = Application()
    appl.Project = prop
    # highestprio = request.user.applications.aggregate(Max('Priority'))['Priority__max']
    appl.Student = request.user
    # if highestprio is None:
    #     appl.Priority = 1
    # else:
    #     appl.Priority = highestprio + 1
    appl.save()
    return render(request, "base.html", context={
        "Message": "Application saved!",
        "return": 'students:list_applications',
    })


@can_view_project
@can_apply
def confirm_apply(request, pk):
    """
    After a student presses apply on a project, he/she has to confirm the application on this page.
    This page also checks whether the user is allowed to apply

    :param request:
    :param pk: id of the project
    """
    prop = get_object_or_404(Project, pk=pk)
    if Application.objects.filter(Q(Project=prop) & Q(Student=request.user)).exists():
        return render(request, "base.html", context={
            "Message": "You already applied to this project.",
            "return": 'students:list_applications',
        })
    return render(request, "students/apply.html", context={
        "project": get_object_or_404(Project, pk=pk),
    })


@login_required()
def list_files(request, dist):
    """
    List all files of a student on a distribution.

    :param request:
    :param dist: distribution to view files from.
    :return:
    """
    dist = get_object_or_404(Distribution, pk=dist)
    if request.user.groups.exists():
        if not (request.user in dist.Project.Assistants.all() or request.user == dist.Project.ResponsibleStaff or get_grouptype('studyadvisors') in request.user.groups.all()):
            # staff
            raise PermissionDenied("You are not allowed to view these student files.")
    elif request.user != dist.Student:
        # student
        raise PermissionDenied("You are not allowed to view this page.")

    files = dist.files.all()
    return render(request, 'students/list_files.html', context={
        'dist': dist,
        'files': files,
    })


@student_only()
def add_file(request, dist):
    """
    For students to upload a file. Used for the hand in system.
    Responsibles, assistants and trackheads can then view the files of their students.
    support staff can see all student files.

    :param request:
    :param dist: Distribution to add file to.
    """
    dist = get_object_or_404(Distribution, pk=dist)
    if request.user != dist.Student:
        raise PermissionDenied("You are not allowed to view this page.")

    if request.method == 'POST':
        form = StudentFileForm(request.POST, request.FILES, request=request)
        if form.is_valid():
            file = form.save(commit=False)
            file.Distribution = dist
            file.save()
            return render(request, 'base.html',
                          {'Message': 'File uploaded!', 'return': 'students:files', 'returnget': dist.pk})
    else:
        form = StudentFileForm(request=request)
    return render(request, 'GenericForm.html',
                  {'form': form, 'formtitle': 'Upload a file ', 'buttontext': 'Save'})


@student_only()
def edit_file(request, dist, file):
    """
    For students to edit a uploaded file. Used for the hand in system.
    Responsibles, assistants and trackheads can then view the files of their students.
    support staff can see all student files.

    :param request:
    :param dist: pk of Distribution of file
    :param file: pk of file
    """
    dist = get_object_or_404(Distribution, pk=dist)
    if request.user != dist.Student:
        raise PermissionDenied("You are not allowed to view this page.")
    file = get_object_or_404(StudentFile, pk=file, Distribution=dist)
    if request.method == 'POST':
        form = StudentFileForm(request.POST, request.FILES, request=request, instance=file)
        if form.is_valid():
            if form.has_changed():
                file = form.save(commit=False)
                file.Distribution = dist
                file.save()
                return render(request, 'base.html',
                              {'Message': 'File changed!', 'return': 'students:files', 'returnget': dist.pk})
            else:
                return render(request, 'base.html',
                              {'Message': 'No change made.', 'return': 'students:files', 'returnget': dist.pk})
    else:
        form = StudentFileForm(request=request, instance=file)
    return render(request, 'GenericForm.html',
                  {'form': form, 'formtitle': 'Edit file ', 'buttontext': 'Save'})

templates/templates/students/apply.html
{% extends "base.html" %}

{% block body %}
    <h1>Confirm application to project.</h1>
    <p>
        After you applied to this project you can retract your application using the applications list.
    </p>
    <table class="table">
        <tr>
            <td>Name project:</td>
            <td>{{ project.Title }}</td>
        </tr>
        <tr>
            <td>Responsible staff:</td>
            <td>{{ project.ResponsibleStaff.usermeta.get_nice_name }}</td>
        </tr>
        <tr>
            <td>Assistants:</td>
            <td>
                {% if project.Assistants.all %}
                    <ul>
                        {% for assistant in project.Assistants.all %}
                            <li>
                                {{ assistant.usermeta.get_nice_name }}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    None
                {% endif %}
            </td>
        </tr>
        <tr>
            <td><a href="{% url 'students:apply' project.id %}">
                <button class="button primary">Apply</button>
            </a></td>
            <td></td>
        </tr>
    </table>
{% endblock %}

templates/templates/students/list_applications.html
{# list own applications for students #}
{% extends "base.html" %}
{% block body %}
    <h1>Applications and distributions</h1>
    <p>After you made an application it is possible to retract the application except when you are distributed to the project.</p>
    <p>If you apply to a project in an other specialization path than yours, contact the supervisor of the project to
        discuss whether it is possible to do the project.</p>
    <p>You can hand in files for your project when you are distributed to the project using the Files button.</p>
    <table class="table datatable striped">
        <thead>
        <tr>
            <th data-priority="1">Name<br/></th>
            <th>Group<br/></th>
            <th>Responsible staff<br/></th>
            <th>Assistant(s)<br/></th>
            <th>Applied</th>
            <th>Distributed</th>
            <th>Project status<br/></th>
            <th data-searchable="false" data-sortable="false" data-priority="2">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for p in projlist %}
            {% with project=p.project %}
                <tr>
                    <td><a href="{% url 'projects:details' project.id %}" class="capitalize">{{ project.Title }}</a>
                    </td>
                    <td>{{ project.Group }}</td>
                    <td>
                        <a href="mailto:{{ project.ResponsibleStaff.email }}">
                            {{ project.ResponsibleStaff.usermeta.get_nice_name }}
                        </a>
                    </td>
                    <td>
                        <ul>
                            {% for a in project.Assistants.all %}
                                <li><a href="mailto:{{ a.email }}">{{ a.usermeta.get_nice_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td data-search="{{ p.application|yesno:"yes,no" }}">
                        <span class="mif-{{ p.application|yesno:"checkmark fg-green,cross fg-red" }}"></span>
                    </td>
                    <td data-search="{{ p.distribution|yesno:"yes,no" }}">
                        <span class="mif-{{ p.distribution|yesno:"checkmark fg-green,cross fg-red" }}"></span>
                    </td>
                    <td data-sort="status{{ project.Status }}">
                        {% if project.Status == 3 %}
                            {{ project.get_Progress_display|default:"not yet started" }}
                        {% else %}
                            Project is not (yet) public.
                        {% endif %}
                    </td>
                    <td>
                        {% if p.distribution %}
                            <a href="{% url 'students:files' p.distribution.id %}">
                                <button class="button primary">Files</button>
                            </a>
                        {% elif p.application %}
                            <a href="{% url 'students:retractapplication' p.application.id %}">
                                <button class="button danger">Retract application</button>
                            </a>
                        {% endif %}

                    </td>
                </tr>
            {% endwith %}
        {% endfor %}
    </table>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {

            $('.datatable').dt_wrapper([
                    {column_number: 1, filter_type: "select"},
                    {column_number: 2, filter_type: "select", column_data_type: 'html'},
                    {
                        column_number: 3,
                        filter_type: "select",
                        column_data_type: 'html',
                        html_data_type: 'selector',
                        html_data_selector: 'li'
                    }, //to parse ul-li
                    {column_number: 4, filter_type: "select", html5_data: 'data-search'},
                    {column_number: 5, filter_type: "select", html5_data: 'data-search'},
                    {column_number: 6, filter_type: "select", html5_data: 'data-search'},  // to parse mailto links
                ]
            );
        });
    </script>  {% endblock %}

templates/templates/students/list_files.html
{% extends "base.html" %}
{% block body %}
    <h1>Files list for {{ dist.Student.usermeta.get_nice_name }}</h1>
    <h2>on project {{ dist.Project }}</h2>
    {% if not request.user.groups.exists %}
        <a href="{% url 'students:addfile' dist.pk %}" class="button primary">Upload new</a>

    {% endif %}
    <table class="table bordered">
        <thead>
        <th></th>
        <th>Caption</th>
        <th>File</th>
        <th>Created</th>
        <th>Updated</th>
        {% if not request.user.groups.exists %}
            <th>Edit</th>
        {% endif %}
        </thead>
        {% for file in files %}
            <tr>
                <td><span class="icon mif-file-{{ file.metro_icon }}"></span></td>
                <td>{{ file.Caption }}</td>
                <td><a href="{% url "download:studentfile" file.id %}" download>{{ file.OriginalName }}</a></td>
                <td data-sort="{{ file.Created|date:"U" }}">{{ file.Created }}</td>
                <td data-sort="{{ file.TimeStamp|date:"U" }}">{{ file.TimeStamp }}</td>
                {% if not request.user.groups.exists %}
                    <td>
                        <a href="{% url 'students:editfile' dist.id file.id %}" class="button primary">Edit</a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>
{% endblock %}