MasterMarketplace/urls.py
"""
MasterMarketplace URL Configuration

"""
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView

admin.autodiscover()
admin.site.login = login_required(admin.site.login)

urlpatterns = [
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    # path('osiris/', include('osiris.urls')),
    path('', include('index.urls')),
    path('accesscontrol/', include('accesscontrol.urls')),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('api/', include('api.urls')),
    path('download/', include('download.urls')),
    path('godpowers/', include('godpowers.urls')),
    path('impersonate/', include('impersonate.urls')),
    path('js_error_hook/', include('django_js_error_hook.urls')),
    path('projects/', include('projects.urls')),
    path('registration/', include('registration.urls')),
    path('students/', include('students.urls')),
    path('studyguide/', include('studyguide.urls')),
    path('support/', include('support.urls')),
    path('tracking/', include('tracking.urls')),
    path('two_factor/', include('two_factor_custom.urls')),
    path('shen/', include('shen_ring.urls')),

]

if settings.DEBUG and False:
    import debug_toolbar

    urlpatterns = [
        path('debug/', include(debug_toolbar.urls)),

    ] + urlpatterns

# static download path, for unprotected downloads. Not used.
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Error handlers.
handler400 = 'index.views.error400'
handler404 = 'index.views.error404'
handler403 = 'index.views.error403'
handler500 = 'index.views.error500'

api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('', views.api_info, name='api'),

    # path('status/upgrade/<int:pk>/', views.upgrade_status_api, name='upgradestatus'),
    # path('status/downgrade/<int:pk>/', views.downgrade_status_api, name='downgradestatus'),
    # path('getgroupadmins/', views.get_group_admins, name='getgroupadmins'),
    # path('getgroupadmins/<str:group>/', views.get_group_admins, name='getgroupadminsarg'),
    path('projects/', views.list_published_api, name='listpublished'),
    path('projects/group/', views.list_public_projects_api, name='listpublishedpergroup'),
    path('projects/titles/', views.list_public_projects_titles_api, name='listpublishedtitles'),
    path('projects/<int:pk>/', views.detail_proposal_api, name='getpublisheddetail'),
    path('getgroupadmins/<slug:type>/', views.get_group_admins, name='getgroupadmins'),
    path('getgroupadmins/<slug:type>/<int:pk>/', views.get_group_admins, name='getgroupadmins'),
    path('verify/assistant/<int:pk>/', views.verify_assistant, name='verifyassistant'),

]

projects/urls.py
from django.urls import path, re_path

from . import views

app_name = 'projects'

urlpatterns = [
    path('list/', views.list_public_projects, name='list'),
    path('favorites/', views.list_favorite_projects, name='favorites'),

    path('list/<str:type_filter>/', views.list_public_projects, name='list'),
    path('favorites/<str:type_filter>/', views.list_favorite_projects, name='favorites'),

    path('group/active/', views.list_group_projects, name='listgroupprojects'),
    path('group/<str:status_filter>/', views.list_group_projects, name='listgroupprojects'),

    path('details/<int:pk>/', views.detail_project, name='details'),
    path('create/', views.create_project, name='create'),
    path('own/active/', views.list_own_projects, name='chooseedit'),  # for if no kwargs given, default to active.
    path('own/<str:status_filter>/', views.list_own_projects, name='chooseedit'),
    path('edit/<int:pk>/', views.edit_project, name='edit'),
    path('copy/<int:pk>/', views.copy_project, name='copy'),

    path('files/add/<str:ty>/<int:pk>/', views.add_file, name='addfile'),
    path('files/edit/<str:ty>/<int:pk>/', views.edit_file, name='editfile'),

    path('delete/ask/<int:pk>/', views.ask_delete_project, name='askdeleteproject'),
    path('delete/<int:pk>/', views.delete_project, name='deleteproject'),

    path('labels/', views.list_labels, name='labels'),
    path('labels/add/', views.add_label, name='createlabel'),
    path('labels/<int:pk>/', views.edit_label, name='editlabel'),
    path('labels/activate/<int:pk>/', views.activate_label, name='activatelabel'),
    path('labels/delete/<int:pk>/', views.delete_label, name='deletelabel'),

    path('status/upgrade/<int:pk>/', views.upgrade_status, name='upgradestatus'),
    path('status/downgrade/<int:pk>/', views.downgrade_status, name='downgradestatusmessage'),

    # cpv
    path('contentpolicy/', views.content_policy_view, name='contentpolicy'),
    path('contentpolicy/calc/', views.content_policy_calc, name='contentpolicycalc'),

    path('pending/', views.list_pending, name='pending'),

    path('share/<int:pk>/', views.share, name='sharelink'),
    re_path(r'^share/(?P<token>[0-9A-Za-z_\-:]+)/$', views.view_share_link, name='viewsharelink'),

    path('distribute/<int:pk>/', views.distribute_project, name='distribute'),
    path('progress/<int:pk>/', views.progress_project, name='progress'),

    path('stats/personal/', views.project_stats_personal, name='stats_personal'),
    path('stats/active/', views.project_stats, name='stats'),  # if no kwarg.
    path('stats/<str:status_filter>/', views.project_stats, name='stats'),

]

projects/models.py
# from channels import Channel
import logging
import re
from datetime import datetime
from hashlib import sha256

from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.contrib.auth.models import User
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import URLValidator
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.html import escape

from general_model import file_delete_default, filename_default, clean_text, get_ext, print_list
from studyguide.models import CapacityGroup, MasterProgram, MainCourse

logger = logging.getLogger('django')
email_regex = re.compile(settings.EMAILREGEXCHECK)
link_regex = re.compile(settings.LINKREGEX)


class ProjectLabel(models.Model):
    """
    Label to categorize projects
    """
    ColorChoices = (
        ("bg-lime", "lime"),
        ("bg-green", "green"),
        ("bg-emerald", "emerald"),
        ("bg-teal", "teal"),
        ("bg-blue", "blue"),
        ("bg-cobalt", "cobalt"),
        ("bg-indigo", "indigo"),
        ("bg-violet", "violet"),
        ("bg-magenta", "magenta"),
        ("bg-crimson", "crimson"),
        ("bg-red", "red"),
        ("bg-orange", "orange"),
        ("bg-amber", "amber"),
        ("bg-yellow", "yellow"),
        ("bg-brown", "brown"),
        ("bg-olive", "olive"),
        ("bg-steel", "steel"),
        ("bg-mauve", "mauve"),
        ("bg-taupe", "taupe"),
        ("bg-gray", "gray"),
        # backup colors, if many labels are needed.
        # ("bg-darkOrange", "darkOrange"),
        # ("bg-darkCrimson", "darkCrimson"),
        # ("bg-darkGreen", "darkGreen"),
        # ("bg-darkEmerald", "darkEmerald"),
        # ("bg-darker", "darker"),
        # ("bg-darkCyan", "darkCyan"),
        # ("bg-darkCobalt", "darkCobalt"),
        # ("bg-darkPink", "darkPink"),
        # ("bg-darkViolet", "darkViolet"),
        # ("bg-darkBlue", "darkBlue"),
        # ("bg-lightBlue", "lightBlue"),
    )
    Name = models.CharField(max_length=50, unique=True)
    Color = models.CharField(max_length=20, choices=ColorChoices)
    Active = models.BooleanField(default=False)

    def clean(self):
        self.Name = clean_text(self.Name)
        # Remove ':' because it is used in string function.
        self.name = self.name.replace(':', '_')

    def __str__(self):
        """
        This format is used by select2 to display the color on the label form.

        :return:
        """
        return '{}:{}'.format(self.Name, self.Color)


class Project(models.Model):
    """
    Model for a project.
    """
    StatusOptions = (
        (1, "Draft, awaiting completion by assistant"),
        (2, "Draft, awaiting approval by responsible staff"),
        (3, "Active project"),
    )

    ApplyOptions = (
        ('system', 'Using master marketplace'),
        ('supervisor', 'By contacting supervisor'),
    )
    ProgressOptions = (
        (1, 'Project is being executed'),
        (2, 'Project is finished'),
        (3, 'Project is reserved'),
    )
    TypeOptions = (
        ('graduation', 'Graduation project'),
        ('internship', 'Internship project'),
        ('both', 'Graduation or internship project'),
    )
    Title = models.CharField(max_length=100)
    ResponsibleStaff = models.ForeignKey(User, on_delete=models.PROTECT, related_name='projectsresponsible')
    Assistants = models.ManyToManyField(User, related_name='projects', blank=True)
    ExternalStaff = models.TextField(blank=True, null=True, help_text='External staff (for instance company contact person). Please put one name and/or email on each line.')
    Group = models.ForeignKey(CapacityGroup, on_delete=models.PROTECT)
    SecondaryGroup = models.ManyToManyField(CapacityGroup, blank=True, related_name='secondarygroupprojects', help_text='One or more secondary capacity groups. Use if a project is shared with multiple capacity groups.')
    NumStudentsMin = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    NumStudentsMax = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    GeneralDescription = models.TextField(
        help_text='General description of the project. Hyperlinks will be tested before publishing.')
    StudentsTaskDescription = models.TextField(
        help_text='Task description of the project. Hyperlinks will be tested before publishing.')
    SiteUrl = models.URLField(blank=True, null=True,
                              help_text='Link to site of the group or other place with more information')
    Status = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(3)],
                                 choices=StatusOptions)
    Progress = models.IntegerField(default=None, blank=True, null=True, choices=ProgressOptions)
    StartDate = models.DateField(blank=True, null=True,
                                 help_text='Set this to the date from when students can view this project. Including this date.')
    EndDate = models.DateField(blank=True, null=True,
                               help_text='Set this to the date till when students can view this project. Visible including this date.')

    Type = models.CharField(default='graduation', max_length=16, choices=TypeOptions,
                            help_text="Choose the type of this project, like internship or graduation.")
    Apply = models.CharField(default='system', max_length=16, choices=ApplyOptions,
                             help_text="Choose whether students can apply to this project using an 'apply' button on the master marketplace or only by directly contacting the supervisor")
    Program = models.ManyToManyField(MasterProgram, related_name='restrictedprojects', blank=True,
                                     help_text='Required specialization path(s) to do this project.')
    RecommendedCourses = models.ManyToManyField(MainCourse, related_name='projects', blank=True,
                                                help_text='Courses recommended to be able to do this project. Leave the field blank if there are no recommended courses.')
    Labels = models.ManyToManyField(ProjectLabel, blank=True, related_name='projects', help_text='Assign category labels to this project.')
    TimeStamp = models.DateTimeField(auto_now=True, null=True)
    Created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        try:
            return '{} from {}'.format(self.Title, self.ResponsibleStaff.usermeta.get_nice_name())
        except:
            return '{} from {}'.format(self.Title, self.ResponsibleStaff.username)

    def num_distributions(self):
        return int(self.distributions.count())

    def test_links(self):
        val = URLValidator()
        channel_layer = get_channel_layer()
        for text in [self.GeneralDescription, self.StudentsTaskDescription]:
            emailreg = re.compile(settings.EMAILREGEXCHECK)
            links = list(link_regex.finditer(text))
            for result in links:
                logger.info('model checks {}'.format(result.group(2)))
                if 'mailto' == result.group(2).split(':')[0]:
                    try:
                        if not emailreg.fullmatch(result.group(2).split(':')[1]):
                            logger.warning('Invalid email: {}'.format(result.group(2)))
                    except:
                        logger.warning('Invalid email: {}'.format(result.group(2)))
                    continue

                try:
                    val(result.group(2))
                except ValidationError:
                    continue
                h = sha256(result.group(2).encode()).hexdigest()
                cache.set('virustotal:owner:' + h, self.ResponsibleStaff.email, None)
                async_to_sync(channel_layer.send)(
                    'virustotal', {
                        'type': 'checklink',
                        'link': result.group(2)
                    }
                )
                # Channel('virustotal.checklink').send({
                #     "link": result.group(2),
                # })

    def clean(self):
        self.Title = clean_text(self.Title)
        self.GeneralDescription = clean_text(self.GeneralDescription)
        self.StudentsTaskDescription = clean_text(self.StudentsTaskDescription)
        self.ExternalStaff = escape(clean_text(self.ExternalStaff))
        self.test_links()

        if self.Status != 3 and self.Progress:
            raise ValidationError("Project being executed or finished needs to have status 3 (active)")

        if self.StartDate:
            if self.Progress and self.StartDate >= datetime.now().date():
                raise ValidationError("Project progress cannot be set on not-yet started projects.")
            if self.EndDate:
                if self.StartDate >= self.EndDate:
                    raise ValidationError("Start date cannot be later or the same as end date visible.")

        min_std = self.NumStudentsMin
        max_std = self.NumStudentsMax
        if min_std and max_std:
            if min_std > max_std:
                raise ValidationError("Minimum number of students cannot be higher than maximum.")
        else:
            raise ValidationError("Min or max number of students cannot be empty")

    def public_visible(self):
        if self.Status == 3:
            if self.StartDate:
                if self.StartDate > datetime.now().date():
                    return False
            if self.EndDate:

templates/templates/projects/cpv_progress.html
{% extends "base.html" %}
{% block body %}
    <h1>Calculating content policy violations for projects</h1>
    <div class="progress large" data-role="progress" id="progressbar"></div>
{#    <div style="border:1px solid black; height:1000px; overflow:scroll;" id="liveview"></div>#}
<a href="{% url 'projects:contentpolicy' %}" class="button primary">View results</a>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            if (window.location.protocol == "https:") {
                window.socket = new WebSocket("wss://" + window.location.host + "/projects/cpvprogress/");
            }
            else {
                window.socket = new WebSocket("ws://" + window.location.host + "/projects/cpvprogress/");
            }
            window.socket.onmessage = function (e) {
                var pb = $("#progressbar").data('progress');
                var info = JSON.parse(e.data);
                {#document.getElementById('liveview').insertAdjacentHTML('afterbegin', info['email'] + "<br/>");#}
                pb.set(info['progress']);
                if(info['progress']>98){
                    window.setTimeout(function(){window.location="{% url 'projects:contentpolicy' %}"}, 500)


                }
            };
        });
    </script>
{% endblock %}

templates/templates/projects/list_labels.html
{% extends "base.html" %}
{% load index_tags %}

{% block body %}
    <h1>Project Labels</h1>
    <p>
        Labels are used to categorize projects. Projects can have multiple labels.
        All staff members can create new (inactive) labels.
        The {{ support_role }} ({{ support_name }}) can edit labels and set inactive labels to active.
    </p>
    <a href="{% url 'projects:createlabel' %}">
        <button class="button primary">Add new</button>

    </a>
    <br/>
    <table class="table striped hovered datatable">
        <thead>
        <th>Label</th>
        <th>Active</th>
        {% if user|has_group:"studyadvisors" %}
            <th>Edit</th>
        {% endif %}
        </thead>
        {% for label in labels %}
            <tr>
                <td><span class="project_label {{ label.Color }}">{{ label.Name }}</span></td>
                <td data-search="{{ label.Active }}">
                    <span class="mif-{{ label.Active|yesno:"checkmark fg-green,cross fg-red" }}"> </span>
                    {% if user|has_group:"studyadvisors" and not label.Active %}
                        <a href="{% url 'projects:activatelabel' label.id %}">
                            <button class="button success">Make active</button>
                        </a>
                    {% endif %}
                </td>
                {% if user|has_group:"studyadvisors" %}
                    <td>
                        <a href="{% url 'projects:editlabel' label.id %}">
                            <button class="button primary">Edit</button>
                        </a>
                        <a href="{% url 'projects:deletelabel' label.id %}">
                            <button class="button danger">Delete</button>
                        </a>
                    </td>
                {% endif %}
            </tr>
        {% endfor %}
    </table>


{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            var dt = $('.datatable').dt_wrapper();
        });
    </script>
{% endblock %}

templates/templates/projects/list_projects_custom.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% load index_tags %}
{% load project_tags %}
{% block body %}
    <h1>
        {% if title %}
            {{ title|capfirst }}
        {% else %}
            {% if user|has_group:'studyadvisors' %}
                All
            {% else %}
                My
            {% endif %}
            {% if status_filters %}
                {{ status_filter|default_if_none:"" }}
            {% endif %}
            projects
        {% endif %}
    </h1>
    {% if status_filters %}
        <div class="tabcontrol">
            <ul class="tabs">
                {% for ts in status_filters %}
                    <li {% if ts == status_filter %}class="active" {% endif %}><a href="{% if ts == status_filter %}#{% else %}../{{ ts }}{% endif %}">{{ ts }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <a href="#" id="studentinfo" class="columnToggle button"><span></span> student info</a>
    <a href="#" id="projectinfo" class="columnToggle button"><span></span> project info</a>

    <div class="double-scroll">
        <table class="table datatable striped">
            <thead>
            <tr>
                <th><span class="mif-star-half icon"></span></th>
                <th data-priority="1">Name</th>
                <th data-visible='false' class="projectinfo">Group</th>
                <th>Responsible staff</th>
                <th data-visible='false' class="projectinfo">Assistant(s)</th>
                <th data-visible='false' class="projectinfo">Type</th>
                <th data-visible='false' class="studentinfo">Applied students</th>
                <th data-visible='false' class="studentinfo">Distributed students</th>
                <th>Status</th>
                <th data-priority="2">Edit</th>
            </tr>
            </thead>
            <tbody>
            {% for project in projects %}
                <tr>
                    <td>
                    <span id="fav-{{ project.pk }}"
                          class="star-favorite mif-star-{% if project.pk in favorite_projects %}full{% else %}empty{% endif %} icon">
                    </span>
                    </td>
                    <td>
                        <a href="{% url 'projects:details' project.id %}">{{ project.Title }}</a><br/>
                        {{ project|project_labels }}
                    </td>
                    <td>{{ project.Group }} {% if project.SecondaryGroup.exists %}({{ project.SecondaryGroup.all|print_list }}){% endif %}</td>
                    <td>
                        <a href="mailto:{{ project.ResponsibleStaff.email }}">
                            {{ project.ResponsibleStaff.usermeta.get_nice_name }}
                        </a>
                    </td>
                    <td>
                        <ul>
                            {% for a in project.Assistants.all %}
                                <li><a href="mailto:{{ a.email }}">{{ a.usermeta.get_nice_name }}</a></li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        {{ project.get_Type_display }}
                    </td>
                    <td>
                        <ul>
                            {% for a in project.applications.all %}

                                <li>
                                    {#                        <span data-role="hint"#}
                                    {#                              data-hint-background="bg-gray"#}
                                    {#                              data-hint-color="fg-white"#}
                                    {#                              data-hint-mode="2"#}
                                    {#                              data-hint="#}
                                    {#                                {% if a %}#}
                                    {#                                    This student has applied to this project with priority {{ a.Priority }}#}
                                    {#                                {% else %}#}
                                    {#                                    The student did not apply for this project.#}
                                    {#                                {% endif %}">#}
                                    {#                            <span class='tag info'>#}
                                    {#                            {% if a %}#}
                                    {#                                {{ a.Priority }}#}
                                    {#                            {% else %}#}
                                    {#                                -#}
                                    {#                            {% endif %}#}
                                    {#                        </span>#}
                                    {#                        </span>#}
                                    <a href="mailto:{{ a.Student.email }}">{{ a.Student.usermeta.get_nice_name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>
                        <ul>
                            {% for a in project.distributions.all %}
                                <li>
                                    {#                        <span data-role="hint"#}
                                    {#                            data-hint-background="bg-gray"#}
                                    {#                            data-hint-color="fg-white"#}
                                    {#                            data-hint-mode="2"#}
                                    {#                            data-hint="#}
                                    {#                                {% if a.Application %}#}
                                    {#                                    This student has applied to this project with priority {{ a.Application.Priority }}#}
                                    {#                                {% else %}#}
                                    {#                                    The student did not apply for this project.#}
                                    {#                                {% endif %}">#}
                                    {#                            <span class='tag info'>#}
                                    {#                            {% if a.Application %}#}
                                    {#                                {{ a.Application.Priority }}#}
                                    {#                            {% else %}#}
                                    {#                                -#}
                                    {#                            {% endif %}#}
                                    {#                        </span>#}
                                    {#                        </span>#}
                                    <a href="mailto:{{ a.Student.email }}">{{ a.Student.usermeta.get_nice_name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td data-sort="status{{ project.Status }}">
                        {{ project.get_Status_display }}{% if project.Status == 3 %},
                            {{ project.get_Progress_display|default:"not yet started" }}
                        {% endif %}
                    </td>
                    <td>
                        {#                    <a href="{% url 'projects:details' project.id %}" class="button primary">View</a>#}
                        {% if project|can_edit_project:user %}
                            <a href="{% url 'projects:edit' project.id %}" class="button info"><span
                                    class="mif-pencil"></span>Edit data</a>
                            {#                    <a href="{% url 'projects:editfile' 'i' project.id %}" class="button info"><span class="mif-images"></span>Edit images</a>#}
                            {#                    <a href="{% url 'projects:editfile' 'a' project.id %}" class="button info"><span class="mif-file-pdf"></span>Edit attachments</a>#}
                        {% endif %}
                        {% if project|can_distribute_project:user %}
                            <a href="{% url 'projects:distribute' project.id %}"
                               class="button info">Distributions</a>
                        {% endif %}
                        {% if project|can_set_progress_project:user %}
                            <a href="{% url 'projects:progress' project.id %}" class="button info">Progress</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script src="{% static "js/websocketbridge.js" %}"></script>
    <script src="{% static "js/favorite.js" %}"></script>
    <script>
        $(document).ready(function () {
            // custom sort for favorite button, https://datatables.net/examples/plug-ins/dom_sort.html
            $.fn.dataTable.ext.order['dom-order-favorite'] = function (settings, col) {
                return this.api().column(col, {order: 'index'}).nodes().map(function (td, i) {
                    return $('span', td).hasClass('mif-star-full') ? '1' : '0';
                });
            };
            // make cols array for datatables
            const l = $("table.datatable th").length;
            const cols = new Array(l);
            for (var i = 0; i < l; i++) {
                cols[i] = null;
            }
            // set first column to custom sort function
            cols[0] = {"orderDataType": "dom-order-favorite"};
            // call datatables with yadcf and the cols array.
            var dt = $('.datatable').dt_wrapper([
                    {column_number: 2, filter_type: "select", filter_match_mode: 'exact'},
                    {column_number: 3, filter_type: "select", column_data_type: 'html'},  // to parse mailto links
                    {
                        column_number: 4,
                        filter_type: "select",
                        column_data_type: 'html',
                        html_data_type: 'selector',
                        html_data_selector: 'li'
                    }, //to parse ul-li
                    {column_number: 5, filter_type: "select"},  //type
                    {
                        column_number: 6,
                        filter_type: "select",
                        column_data_type: 'html',
                        html_data_type: 'selector',
                        html_data_selector: 'li'
                    }, //to parse ul-li
                    {column_number: 8, filter_type: "select"},
                ], cols
            );

            // event handlers for hide/show buttons
            $(".columnToggle").click(function () {
                //reset width:
                $(".datatable").width("100%");
                // Get the column API object
                var columns = dt.columns("." + $(this).attr('id'));
                // Toggle the visibility
                if (columns.visible()[0]) {
                    columns.visible(false);
                    $(this).find("span").text("Show");
                } else {
                    columns.visible(true);
                    $(this).find("span").text("Hide")
                }
                //trigger resize event for double-scroll because table width has changed.
                $('.double-scroll').trigger('resize.doubleScroll');
            });

            //set default text for columns buttons, because datatables saves visibility in state.
            var but = $('a.columnToggle');
            but.each(function (i) {
                var vis = dt.columns("." + $(this).attr('id')).visible()[0];
                if (vis) {
                    $(this).find("span").text("Hide")
                } else {
                    $(this).find("span").text("Show")
                }
            })
        });
    </script>
{% endblock %}